cpu-bind=MASK - n2gpu1212, task  0  0 [263432]: mask |BBBBBBBB|--------||--------|--------||--------|--------||--------|--------||||BBBBBBBB|--------||--------|--------||--------|--------||--------|--------|  set
cpu-bind=MASK - n2gpu1212, task  0  0 [263480]: mask |BBBBBBBB|--------||--------|--------||--------|--------||--------|--------||||BBBBBBBB|--------||--------|--------||--------|--------||--------|--------|  set
cpu-bind=MASK - n2gpu1213, task  1  0 [2021213]: mask |BBBBBBBB|--------||--------|--------||--------|--------||--------|--------||||BBBBBBBB|--------||--------|--------||--------|--------||--------|--------|  set
master_addr is only used for static rdzv_backend and when rdzv_endpoint is not specified.
master_addr is only used for static rdzv_backend and when rdzv_endpoint is not specified.
[default0]:Traceback (most recent call last):
[default0]:  File "/scratch/hpc-prf-lola/nikit/repos/Megatron-DeepSpeed-BigScience/pretrain_gpt.py", line 20, in <module>
[default0]:    from megatron import get_args
[default0]:  File "/scratch/hpc-prf-lola/nikit/repos/Megatron-DeepSpeed-BigScience/megatron/__init__.py", line 28, in <module>
[default0]:    from .global_vars import get_args
[default0]:  File "/scratch/hpc-prf-lola/nikit/repos/Megatron-DeepSpeed-BigScience/megatron/global_vars.py", line 28, in <module>
[default0]:Traceback (most recent call last):
[default0]:  File "/scratch/hpc-prf-lola/nikit/repos/Megatron-DeepSpeed-BigScience/pretrain_gpt.py", line 20, in <module>
[default0]:    from megatron import get_args
[default0]:  File "/scratch/hpc-prf-lola/nikit/repos/Megatron-DeepSpeed-BigScience/megatron/__init__.py", line 28, in <module>
[default0]:    from .global_vars import get_args
[default0]:  File "/scratch/hpc-prf-lola/nikit/repos/Megatron-DeepSpeed-BigScience/megatron/global_vars.py", line 28, in <module>
[default0]:    from megatron.tokenizer import build_tokenizer
[default0]:  File "/scratch/hpc-prf-lola/nikit/repos/Megatron-DeepSpeed-BigScience/megatron/tokenizer/__init__.py", line 17, in <module>
[default0]:    from .tokenizer import build_tokenizer
[default0]:  File "/scratch/hpc-prf-lola/nikit/repos/Megatron-DeepSpeed-BigScience/megatron/tokenizer/tokenizer.py", line 20, in <module>
[default0]:    from transformers import AutoTokenizer
[default0]:ModuleNotFoundError: No module named 'transformers'
[default0]:    from megatron.tokenizer import build_tokenizer
[default0]:  File "/scratch/hpc-prf-lola/nikit/repos/Megatron-DeepSpeed-BigScience/megatron/tokenizer/__init__.py", line 17, in <module>
[default0]:    from .tokenizer import build_tokenizer
[default0]:  File "/scratch/hpc-prf-lola/nikit/repos/Megatron-DeepSpeed-BigScience/megatron/tokenizer/tokenizer.py", line 20, in <module>
[default0]:    from transformers import AutoTokenizer
[default0]:ModuleNotFoundError: No module named 'transformers'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2021290) of binary: /scratch/hpc-prf-lola/lib_repo/conda-libs/envs/dstorch/bin/python
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 263557) of binary: /scratch/hpc-prf-lola/lib_repo/conda-libs/envs/dstorch/bin/python
Traceback (most recent call last):
  File "/scratch/hpc-prf-lola/lib_repo/conda-libs/envs/dstorch/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/scratch/hpc-prf-lola/lib_repo/conda-libs/envs/dstorch/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/scratch/hpc-prf-lola/lib_repo/conda-libs/envs/dstorch/lib/python3.9/site-packages/torch/distributed/run.py", line 798, in <module>
Traceback (most recent call last):
  File "/scratch/hpc-prf-lola/lib_repo/conda-libs/envs/dstorch/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/scratch/hpc-prf-lola/lib_repo/conda-libs/envs/dstorch/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/scratch/hpc-prf-lola/lib_repo/conda-libs/envs/dstorch/lib/python3.9/site-packages/torch/distributed/run.py", line 798, in <module>
    main()
  File "/scratch/hpc-prf-lola/lib_repo/conda-libs/envs/dstorch/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    main()
  File "/scratch/hpc-prf-lola/lib_repo/conda-libs/envs/dstorch/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/scratch/hpc-prf-lola/lib_repo/conda-libs/envs/dstorch/lib/python3.9/site-packages/torch/distributed/run.py", line 794, in main
    return f(*args, **kwargs)
  File "/scratch/hpc-prf-lola/lib_repo/conda-libs/envs/dstorch/lib/python3.9/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/scratch/hpc-prf-lola/lib_repo/conda-libs/envs/dstorch/lib/python3.9/site-packages/torch/distributed/run.py", line 785, in run
    run(args)
  File "/scratch/hpc-prf-lola/lib_repo/conda-libs/envs/dstorch/lib/python3.9/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/scratch/hpc-prf-lola/lib_repo/conda-libs/envs/dstorch/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    elastic_launch(
  File "/scratch/hpc-prf-lola/lib_repo/conda-libs/envs/dstorch/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/scratch/hpc-prf-lola/lib_repo/conda-libs/envs/dstorch/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/scratch/hpc-prf-lola/lib_repo/conda-libs/envs/dstorch/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
pretrain_gpt.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-04-12_15:53:26
  host      : n2gpu1213.ab2021.local
  rank      : 1 (local_rank: 0)
  exitcode  : 1 (pid: 2021290)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
pretrain_gpt.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-04-12_15:53:26
  host      : n2gpu1212.ab2021.local
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 263557)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
srun: error: n2gpu1212: task 0: Exited with exit code 1
srun: launch/slurm: _step_signal: Terminating StepId=3376540.0
srun: error: n2gpu1213: task 1: Terminated
srun: Force Terminated StepId=3376540.0
